version: "3.2"
services:
  db:
      image: postgres
      ports:
      - "5432:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: movies_db
  app:
    command: npm start
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1918:${PORT}
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_DEV_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:5432/movies_db
      OMDB_API_KEY: ${OMDB_API_KEY}
